### ISSUE TITLE
Android Camera Issue

### ISSUE THREAD

**Issue by Jaew00Shin** [alamin-karno/flutter-crisp-chat#11]
**Describe the bug**

```
I/ViewRootImpl@9facadc[ChatActivity]( 4566): ViewPostIme pointer 0
I/ViewRootImpl@9facadc[ChatActivity]( 4566): ViewPostIme pointer 1
D/AndroidRuntime( 4566): Shutting down VM
E/AndroidRuntime( 4566): FATAL EXCEPTION: main
E/AndroidRuntime( 4566): Process: com.cartlabs.spmarket, PID: 4566
E/AndroidRuntime( 4566): java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.sec.android.app.camera/.Camera clip={text/uri-list U:content://com.cartlabs.spmarket.im.crisp.client.uploadfileprovider/attachments/IMG_20240601_2346326612271636367501836.jpg} (has extras) } from ProcessRecord{aa8c924 4566:com.cartlabs.spmarket/u0a549} (pid=4566, uid=10549) with revoked permission android.permission.CAMERA
E/AndroidRuntime( 4566): 	at android.os.Parcel.createException(Parcel.java:2088)
E/AndroidRuntime( 4566): 	at android.os.Parcel.readException(Parcel.java:2056)
E/AndroidRuntime( 4566): 	at android.os.Parcel.readException(Parcel.java:2004)
E/AndroidRuntime( 4566): 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4454)
E/AndroidRuntime( 4566): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
E/AndroidRuntime( 4566): 	at android.app.Activity.startActivityForResult(Activity.java:5258)
E/AndroidRuntime( 4566): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
E/AndroidRuntime( 4566): 	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:854)
E/AndroidRuntime( 4566): 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:245)
E/AndroidRuntime( 4566): 	at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:239)
E/AndroidRuntime( 4566): 	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:173)
E/AndroidRuntime( 4566): 	at androidx.fragment.app.Fragment$10.launch(Fragment.java:3621)
E/AndroidRuntime( 4566): 	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.v.e.a(SourceFile:15)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.v.e.$r8$lambda$bd0p-dqfkeJm7bsr-7bUJzmpDks(Unknown Source:0)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.v.e$$ExternalSyntheticLambda3.onFragmentResult(Unknown Source:2)
E/AndroidRuntime( 4566): 	at androidx.fragment.app.FragmentManager$LifecycleAwareResultListener.onFragmentResult(FragmentManager.java:249)
E/AndroidRuntime( 4566): 	at androidx.fragment.app.FragmentManager.setFragmentResult(FragmentManager.java:925)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.w.a.a(SourceFile:4)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.w.a.a(SourceFile:2)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.w.a.$r8$lambda$wO-ee-KTxaeYOqhu113w8eiTdtc(Unknown Source:0)
E/AndroidRuntime( 4566): 	at im.crisp.client.internal.w.a$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
E/AndroidRuntime( 4566): 	at android.view.View.performClick(View.java:7862)
E/AndroidRuntime( 4566): 	at android.widget.TextView.performClick(TextView.java:15004)
E/AndroidRuntime( 4566): 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
E/AndroidRuntime( 4566): 	at android.view.View.performClickInternal(View.java:7831)
E/AndroidRuntime( 4566): 	at android.view.View.access$3600(View.java:879)
E/AndroidRuntime( 4566): 	at android.view.View$PerformClick.run(View.java:29359)
E/AndroidRuntime( 4566): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 4566): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 4566): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 4566): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime( 4566): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4566): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime( 4566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/AndroidRuntime( 4566): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 4566): 	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1447)
E/AndroidRuntime( 4566): 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:980)
E/AndroidRuntime( 4566): 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
E/AndroidRuntime( 4566): 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2074)
E/AndroidRuntime( 4566): 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)
E/AndroidRuntime( 4566): 
I/Process ( 4566): Sending signal. PID: 4566 SIG: 9
Lost connection to device.
the Dart compiler exited unexpectedly.
```

**To Reproduce**
This issue occurs only in Android.
1. Open Crisp Chat
2. press 'Take Photo' Button
3. Then application is terminated unexpectedly.

**Expected behavior**
The camera application should be opened.

**Desktop (please complete the following information):**
 - OS: Android
 - Version
 crisp_chat: ^2.0.1
permission_handler: ^11.3.1

**Smartphone (please complete the following information):**
 - Device: Galaxy S9+
 - OS: Android10

**Additional context**
`<uses-permission android:name="android.permission.CAMERA" />`

I have already camera permission in `AndroidManifest.xml`

**Comment by alamin-karno** [comment]
Thanks for describe well the full issue. 

# Solution: 

`android:exported="true"`


You need to set `android:exported="true"` in your `AndroidManifest.xml` file where you declare this `Activity`:

    <activity
        android:name="com.example.MainActivity"
        android:label="LibMain" 
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" >
            </action>
        </intent-filter>
    </activity>
